title: Aryan Mukherjee
logo: /assets/img/headshot_circle.png
description: |
  Hey there! I'm Aryan Mukherjee, a Data Analytics graduate from Langara College in Vancouver, where I proudly earned a spot on the Dean's Honour Roll with a 3.52 GPA. I’m passionate about transforming data into actionable insights and have a strong foundation in statistics, machine learning, and data visualization.

  From troubleshooting tech issues as a Geek Squad agent at BestBuy to streamlining business processes and data management as a Business Analyst, I’ve learned how to solve problems and drive improvements through data. I’ve also tackled exciting projects, such as predicting heart disease and analyzing electric vehicle battery performance. My skills span Python, SQL, and R, and I’m always exploring new tools and methods to level up my analytical game.

  When I’m not diving into data or fine-tuning models, I’m exploring innovations in healthcare analytics and sustainable technology. Always learning, always evolving, and always ready to take on the next challenge!
show_downloads: true
theme: jekyll-theme-minimal
