title: Aryan Mukherjee
logo: /Image/PIC.jpg
description: |
  Hey, I'm Aryan Mukherjee! Data isn’t just numbers to me — it’s about uncovering the truth behind the scenes. It’s a capital mistake to theorize before one has data, right? This quote from Sherlock Holmes perfectly sums up why I got into this field: the facts lead the way.

  When I’m not working on data, you’ll find me gaming or reading manga (yes, I know, big surprise, right?). I thrive on challenges and love the process of tackling tough problems head-on. The more complex, the better!

  Always learning, always evolving, and always up for the next challenge. Let’s see what insights we can uncover together!
show_downloads: False
theme: jekyll-theme-minimal
